### ISSUE TITLE
OMG, please revert back to ba2b496e072ba36f77d4550ecd7c89fb06735d4b

### ISSUE THREAD

**Issue by marc-ostrow** [ziutek/dvb#13]
Michal, you were so kind to respond so quickly to my PR.  Thank you, but OMG, I'm so sorry!  I just reread my comments on the PR

> Typical Headers look as follows.
> ```
> [000001bd002c81800525339fe61f305f31385f323134323837373434315f32355f313631363930323031393339393131380a]
> [000001bd002c81800525339ffd95305f31395f323134323838343136335f32355f313631363930323031393431383338360a]
> [000001bd002c8180052533a1150b305f32305f323134323839323533315f32355f313631363930323031393435393937350a]
> ```
> stream_id is 0xbd, Flags are present, PTS is present
> 

"**Flags are present**" !!!!

I honestly don't know what I was seeing, _HasFlags() is clearly returning a false value when any of the listed stream IDs is present_.  Stream ID 0xbd, has flags, at least in the streams we are receiving!

I sent two emails, but either both were to bogus addresses, or you've been too busy to see.  So not as quietly as it might have been if you had noticed my emails, would you please, roll back PR #12.

Thank you!

**Comment by embeddedgo** [comment]
Done. Thanks!

**Comment by ziutek** [comment]
Done. Thanks!

**Comment by marc-ostrow** [comment]
Michal,

I do not believe we've successfully rolled back Pull Request #12.
 Essentially, given the activity in the repository, commit on April 24th,
2020 (ba2b496e072ba36f77d4550ecd7c89fb06735d4b) should be the HEAD of the
repository.  All commits after that are related to merging PR #12, and
trying to undo it, but we did not.

The effective change if not doing a forced reset
to ba2b496e072ba36f77d4550ecd7c89fb06735d4b, *would have been to roll back
to the previous version of ts/pes/pes.go*.

I'm feeling quite sorry I got us into this mess!

Thank you,

Marc

**Comment by ziutek** [comment]
I've just reset to ba2b496e072ba36f77d4550ecd7c89fb06735d4b. The history was changed but it isn't very popular repository so I think it shouldn't be a big problem.

**Comment by marc-ostrow** [comment]
The only activity since April 2020 was my blunder! ;-)

However, out of the existing repositories on the subject, I happen to like
this one the best.  I like its simplicity.  We were using Comcast's gots (
https://github.com/Comcast/gots)
