### ISSUE TITLE
Analyze mpeg-ts stream

### ISSUE THREAD

**Issue by o1egl** [ziutek/dvb#4]
Hi. I'm newly to mpeg-ts and need your help. I have udp multicast of mpeg-ts streams (SS and MS). How can I analyze this streams? For example how to parse that MS stream and get useful information about channels, errors and etc ?

``` go
addr, _ := net.ResolveUDPAddr("udp","233.76.175.7:1234")
conn, _ := net.ListenMulticastUDP("udp", nil, addr)

tsReader := ts.NewPktStreamReader(ServerConn)
pkt := new(ts.ArrayPkt)

for {
        if err := tsReader.ReadPkt(pkt); err != nil {
            log.Error(err)
        }
        if pkt.ContainsError() {
            log.Error("contains error")
        }
    }
```

**Comment by ziutek** [comment]
1. You don't need PktStreamReader in case of UDP. Use PktPktReader instead.

2. You need some (substantially greater than zero) knowledge about MPEG-TS and especially PSI to use this library. Search for and download something like iso13818.pdf and read it.

3. Read issue #3 to see how parse PSI tables.
